# Use the official Node.js image
FROM node:latest

# Set the working directory
WORKDIR /app

# Install dependencies
RUN npm install

# Copy the entire project to the container's working directory
COPY . .

# Expose the application port
EXPOSE 3000

# Command to run the Next.js development server
CMD ["npm", "run", "dev"]